language: php

php:
  - 5.6
  - 7.0
#  disable since phpunit break
#  - 7.1


matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true


install:
  - composer install --dev --no-interaction


script:
 - mkdir -p build/logs
 - composer test
